[pyprland]
plugins = [
  "scratchpads",
  "wallpapers",
]

[scratchpads.term]
animation = "fromTop"
class = "kitty-term"
command = "kitty"
size = "50% 50%"
position = "25% 10%"
unfocus = "hide"


[wallpapers]
unique = true
path = "~/Pictures/wallpapers/"
interval = 5
